---
- hosts: gui
  become: yes
  tasks:
    - name: install vsftpd on ubuntu
      apt: name=vsftpd update_cache=yes state=latest
      ignore_errors: yes 
      notify: start vsftpd 

    - name: install vsftpd on ubuntu
      yum: name=vsftpd  state=latest
      ignore_errors: yes
      notify: start vsftpd
 
    
    handlers:
     - names: start vsftpd  
       service: name=vsftpd enabled=yes state=started
