---
- hosts: all
  become: yes
  tasks:
    - name: update apt
      apt: upgrade=dist update_cache=yes
      when: ansible_os_family == "Debian"
  
    - name: update yum
      yum: name=* state=latest 
      when: ansible_os_family == "RedHat"
